### ISSUE TITLE
INTEGRATE RETURNED ERROR

### ISSUE THREAD

**Issue by vijaykumarsagar** [geoschem/geos-chem#1748]
### Name and Institution (Required)

Name: Vijay Sagar
Institution: Indian Institute of Tropical Meteorology, Pune, India

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)
Confirmed.  
### Description of your issue or question

Dear GEOS-Chem community,
I am writing to address an error that has been reported in GEOS-Chem Classic version 14.1.1. I am running the model with a 4x5 degree resolution with full chemistry. I will work on the high resolution later; currently, I am trying to set the model for low resolution.
The model was installed successfully. All the necessary input files were already downloaded and provided to the model. In the end, when I am running the model by command "./gcclassic", it shows the following error:

```console
Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=   1520.92916351277      and H=  1.062369526925301E-012
 ### INTEGRATE RETURNED ERROR AT:           56          23         
```

I have tried to solve this issue from the link [KPP solvers FAQ](https://wiki.seas.harvard.edu/geos-chem/index.php/KPP_solvers_FAQ) and [BUG/ISSUE](https://github.com/geoschem/geos-chem/issues/191). 
Could you please help me to resolve this error? I would greatly appreciate any guidance/support that you can provide.

[geoschem_config_yml.txt](https://github.com/geoschem/geos-chem/files/11200930/geoschem_config_yml.txt)
[HEMCO_Config_rc.txt](https://github.com/geoschem/geos-chem/files/11200931/HEMCO_Config_rc.txt)
[HEMCO_Config_rc_gmao_metfields.txt](https://github.com/geoschem/geos-chem/files/11200932/HEMCO_Config_rc_gmao_metfields.txt)
[History_rc.txt](https://github.com/geoschem/geos-chem/files/11200933/History_rc.txt)
[log_file.txt](https://github.com/geoschem/geos-chem/files/11200934/log_file.txt)

**Comment by msulprizio** [comment]
Hi @vijaykumarsagar. Please see https://github.com/geoschem/geos-chem/pull/1698 for a fix that should resolve this error.

**Comment by yantosca** [comment]
Hi @vijaykumarsagar, thanks for writing.  I just ported some content from the GEOS-Chem wiki to ReadTheDocs.  Please see this link for some more information:

- https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/error-guide.html#forced-exit-from-rosenbrock

**Comment by vijaykumarsagar** [comment]
Hi Bob and Melissa, Thank you for your kind response. I have implemented the above suggestions such as checking the corrupted input files as suggested in the link. I have reduced as well as increased and increased the RTOL and ATOL values in (GeosCore/fullchem_mod.F90 and GeosCore/mercury_mod.F90) and then compile the model again. I reinstalled model 14.2.0 and downloaded all of the input data to a separate folder, but the issue persists, and it still shows the same error. 
Please briefly describe the changes I need to make in the [1698](https://github.com/geoschem/geos-chem/pull/1698)
and provide further information to help me. 

[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/11234432/HEMCO_Config.rc.txt)
[HEMCO_Diagn.rc.txt](https://github.com/geoschem/geos-chem/files/11234433/HEMCO_Diagn.rc.txt)
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/11234434/HISTORY.rc.txt)
[logfile.txt](https://github.com/geoschem/geos-chem/files/11234435/logfile.txt)
[species_database.yml.txt](https://github.com/geoschem/geos-chem/files/11234436/species_database.yml.txt)
[HEMCO_Config.rc.gmao_metfields.txt](https://github.com/geoschem/geos-chem/files/11234437/HEMCO_Config.rc.gmao_metfields.txt)

**Comment by yantosca** [comment]
Thanks for the feedback @vijaykumarsagar.  We have recently made a fix going into 14.2.0 that shuts off some sea salt hetchem reactions in the stratosphere, which can lead to numerical instability.  Please see the fixes described in PR #1779.

**Comment by vijaykumarsagar** [comment]
Thank you, Bob and team, for your support. I just tried with the latest source code, but it still shows the same integration error.
`git checkout tags/14.2.0-alpha.12

out 'tags/14.2.0-alpha.12'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at d612b79 GEOS-Chem submodule update: Add fixes to avoid KPP integration errors`

Here is the error.:
`# Interpolating Linoz fields for jul
###############################################################################
     - LINOZ_CHEM3: Doing LINOZ
---> DATE: 2019/07/01  UTC: 00:10  X-HRS:      0.166667
HEMCO WARNING: No further attempts will be made to read file: ./HEMCO_restart.$YYYY$MM$DD$HH00.nc
--> LOCATION: HCOIO_READ (HCOIO_READ_STD_MOD.F90)
---> DATE: 2019/07/01  UTC: 00:20  X-HRS:      0.333333
 Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=   1099.67517000074      and H=  8.169766130298750E-013
 ### INTEGRATE RETURNED ERROR AT:           62          13           1
     - DO_LINEAR_CHEM: Linearized chemistry at 2019/07/01 00:20
     - LINOZ_CHEM3: Doing LINOZ`
I have not tried to correct it by changing RTOL and ATOL values, since I have tried many times before, but failed. If possible, can you suggest what values for RTOL and ATOL should be taken? 
Here are the logrun, HISTORY, HEMCO Config, and Config.yml files for your reference.
Best regards,
Vijay
   
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/11400231/HISTORY.rc.txt)
[log.run.txt](https://github.com/geoschem/geos-chem/files/11400232/log.run.txt)
[geoschem_config.yml.txt](https://github.com/geoschem/geos-chem/files/11400233/geoschem_config.yml.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/11400234/HEMCO_Config.rc.txt)
