### ISSUE TITLE
[BUG/ISSUE] How to get HEMCO to read Vertical Coordinates

### ISSUE THREAD

**Issue by lfreese** [geoschem/geos-chem#391]
## Describe the bug:
I'm working on new emissions files and have tried a number of ways to get the vertical allocation of levels to be read into HEMCO, but consistently am getting all emissions at the surface level.

### Expected behavior: ###
With the current setup of the input files, I would expect there to be up to 11 vertical levels of emissions in the HEMCO diagnostics file for Anthro/Bioburn.

### Actual behavior: ###
There are emissions only at lev =0, after which all emissions go to zero for my files. Pictures below show my HEMCO diagnostic for January 1, 2016 for multiple levels. The 'new' file is my emissions file; the 'old' is the original NEI that is in HEMCO traditionally. You can see that the 'old' version is read in correctly, but the 'new' is not. Understandably, above lev = 2 (in python), we do not have emissions from the 'old' version, but we should from the 'new'.

<img width="743" alt="Screen Shot 2020-07-29 at 3 25 30 PM" src="https://user-images.githubusercontent.com/50365319/88843854-c272b200-d1af-11ea-8468-7b801cefb1c2.png">
<img width="821" alt="Screen Shot 2020-07-29 at 3 20 10 PM" src="https://user-images.githubusercontent.com/50365319/88843880-cbfc1a00-d1af-11ea-98f3-0025ea58913f.png">
<img width="860" alt="Screen Shot 2020-07-29 at 3 20 36 PM" src="https://user-images.githubusercontent.com/50365319/88843889-cef70a80-d1af-11ea-98a7-0b4da778e946.png">

### Steps to reproduce: the bug:
This is an example of the HEMCO_Config.rc call: 

0 EPA16_NO__pteguNO $ROOT/NEI2016fh/output/2016fh_16j_emln_ptegu_0pt1degree_3D_month_$MM.ncf  NO       2016-2016/1-12/1/0 C xyz  kgNO2/m2/s  NO   115/25/210/1007     1/2 50

These are the attributes for lev in the file:
<img width="716" alt="Screen Shot 2020-07-28 at 9 43 39 AM" src="https://user-images.githubusercontent.com/50365319/88844214-55abe780-d1b0-11ea-9907-0705f3412915.png">

I have tried two different dimensions: 
1. (lat: 400, lev: 11, lon: 850, nhyi: 12, nhym: 11, time: 1)
2. (lat: 400, lev: 11, lon: 850, time: 1)

### Your GEOS-Chem version and runtime environment:

 - GEOS-Chem version: 12.8.0
 - Compiler version: intel/2017.0.1
 - Did you run on a computational cluster, on the AWS cloud: __cluster
 - Are you using GEOS-Chem "out of the box" (i.e. unmodified): __yes, aside from changing input files

### Input and log files to attach

 - lastbuild: __
 - input.geos: __
 - HEMCO_Config.rc: __
 - HEMCO.log: __

[HEMCO.log](https://github.com/geoschem/geos-chem/files/4997053/HEMCO.log)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/4997068/HEMCO_Config.rc.txt)
[lastbuild.rtf.txt](https://github.com/geoschem/geos-chem/files/4997063/lastbuild.rtf.txt)
[input.geos.rtf.txt](https://github.com/geoschem/geos-chem/files/4997065/input.geos.rtf.txt)

**Comment by yantosca** [comment]
Thanks for writing.  You can distribute in the vertical using the xyL option.  For example, the QFED emissions are set up this way.  (NOTE: I removd the filename so as not to make the lines too long):
```
0 QFED_ACET_PBL ... biomass 2000-2017/1-12/1-31/0 C xyL=1:PBL     kg/m2/s ACET 75/311        5 2
0 QFED_ACET_FT  ... biomass 2000-2017/1-12/1-31/0 C xyL=PBL:5500m kg/m2/s ACET 75/312        5 2
```
So xyL=1:PBL can specify up to the PBL top.  Or xyL=5500m up to a certain height.  I think there is also a way to specify a number of levels too.

**Comment by yantosca** [comment]
NOTE: I think the NEI2011 emissions have irregular vertical levels so that may not be working with the standard vertical interpolation.  (@msulprizio?)

**Comment by lfreese** [comment]
Hi Bob,

Thanks for the response. I think I am confused since some HEMCO emissions files use xyz coordinates and are able to read in emissions at different levels directly from the netcdf. Since the files I made have levels specified as well, I assumed that using the xyz coordinate would similarly mean that emissions would be read according to the 'lev' dimension in my netcdf files. But it seems that this is not the case. I am wondering then how the netcdf files that do work with 'lev' and xyz coordinates are able to be read in properly along the vertical coordinates?

I tried to mimic the above example by running it with: 

```0 EPA16_NO__pteguNO ... NO 2016-2016/1-12/1/0 C xyL=1:11 kgNO2/m2/s NO 115/25/210/1007 1/2 50```

But it still assigns all of my emissions to the first level, and I get results similar to those I described above. My netcdf file already has each of my 11 levels assigned.

**Comment by yantosca** [comment]
Hi Lyssa.  Can you do
```
ncdump -cts filename.nc
```
on a sample emissions file that you are using and post that here?  I'd like to see the metadata.

**Comment by lfreese** [comment]
Definitely. I attached the output in a txt file below:


[\2016fh_16j_emln_ptegu_0pt1degree_3D_month_01.txt](https://github.com/geoschem/geos-chem/files/5002716/2016fh_16j_emln_ptegu_0pt1degree_3D_month_01.txt)

**Comment by yantosca** [comment]
I looked at (what I thought was) a corresponding file in HEMCO/NEI2011/v2015-03:

```
netcdf NEI11_0.1x0.1_20110114_egu {
dimensions:
        time = 24 ;
        lev = 3 ;
        lat = 400 ;
        lon = 900 ;
variables:
        float time(time) ;
                time:calendar = "standard" ;
                time:units = "hours since 2011-01-14 00:00:00" ;
                time:long_name = "Time" ;
                time:_Storage = "chunked" ;
                time:_ChunkSizes = 24 ;
                time:_DeflateLevel = 5 ;
                time:_Shuffle = "true" ;
                time:_Endianness = "little" ;
        int lev(lev) ;
                lev:long_name = "GEOS-Chem levels" ;
                lev:units = "model level" ;
                lev:positive = "up" ;
                lev:_Storage = "chunked" ;
                lev:_ChunkSizes = 3 ;
                lev:_DeflateLevel = 5 ;
                lev:_Shuffle = "true" ;
                lev:_Endianness = "little" ;
. . . etc . . .
 lev = 0, 1, 2 ;
```
If I remember right, if the long name is "GEOS-Chem levels", then HEMCO will attempt to interpret this as the vertical coordinates being on GEOS-Chem levels.  But I am not sure if that'd work if the data does not correspond to the GEOS-Chem levels.

Am tagging @msulprizio and @jimmielin who may know more about this.

**Comment by jimmielin** [comment]
Yes, if the long name is `GEOS-Chem level` or `GEOS-Chem levels` it will be interpreted as model levels (and interpolated to WRF-GC / CESM model levels on these models!)

This is according to HEMCO's `hco_ncdf_mod.F90`. Also note that 47 or 72 levels (or +1) in the file will also auto-recognize as model levels:
```fortran
       ! See if this is a GEOS-Chem model level
       IF ( INDEX(TRIM(LngName),"GEOS-Chem level") > 0 ) THEN
          IsModelLevel = .TRUE.
       ENDIF
```

In `hco_interp_mod.F90`:
```fortran
    ! Assume model levels if input data levels correspond to # of grid
    ! levels or levels + 1 (edges)
    IF ( nlev == nz .OR. nlev == nz + 1 ) THEN
       IsModelLev = .TRUE.
       RETURN
    ENDIF

    ! Other supported levels that depend on compiler flags
    ! Full grid
    IF ( nz == 72 ) THEN
       IF ( nlev <= 73 ) THEN
          IsModelLev = .TRUE.
       ENDIF

    ! Reduced grid
    ELSEIF ( nz == 47 ) THEN
       IF ( nlev == 72 .OR. &
            nlev == 73 .OR. &
            nlev <= 47       ) THEN
          IsModelLev = .TRUE.
       ENDIF
    ENDIF
```

If these are **not** model levels, the models have to be specified as **sigma levels**. This is in `hco_ncdf_mod.F90`:
```fortran
    IF ( TRIM(stdname) == 'atmosphere_hybrid_sigma_pressure_coordinate' ) THEN

       IF ( PRESENT(SigLev4) ) THEN
          CALL NC_GET_SIG_FROM_HYBRID ( fID,  levName, lon1, lon2, lat1, lat2, &
                                        lev1, lev2,    time, dir, RC, SigLev4=SigLev4 )
       ELSEIF ( PRESENT(SigLev8) ) THEN
          CALL NC_GET_SIG_FROM_HYBRID ( fID,  levName, lon1, lon2, lat1, lat2, &
                                        lev1, lev2,    time, dir, RC, SigLev8=SigLev8 )
       ELSE
          WRITE(*,*) 'SigLev array is missing!'
```

Thus the standard name has to be `atmosphere_hybrid_sigma_pressure_coordinate`.
The following variables need to be present in this case:
```
! double lev(lev) ;\\
!        lev:standard_name = "atmosphere_hybrid_sigma_pressure_coordinate" ;\\
!        lev:units = "level" ;\\
!        lev:positive = "down" ;\\
!        lev:formula_terms = "ap: hyam b: hybm ps: PS" ;\\
! double hyam(nhym) ;\\
!        hyam:long_name = "hybrid A coefficient at layer midpoints" ;\\
!        hyam:units = "hPa" ;\\
! double hybm(nhym) ;\\
!        hybm:long_name = "hybrid B coefficient at layer midpoints" ;\\
!        hybm:units = "1" ;\\
! double time(time) ;\\
!        time:standard_name = "time" ;\\
!        time:units = "days since 2000-01-01 00:00:00" ;\\
!        time:calendar = "standard" ;\\
! double PS(time, lat, lon) ;\\
!        PS:long_name = "surface pressure" ;\\
!        PS:units = "hPa" ;\\
```

Hope this helps!
Haipeng

**Comment by lfreese** [comment]
Thanks! I don't have the PS as a variable yet, so this might be the source of the problem. I'll try to add that in and let you know how that works.

**Comment by lfreese** [comment]
Hi @jimmielin --I tried updating and adding a PS, and making sure that the variables you suggested are present, but still am hitting this issue where the HEMCO diagnostics come out just on the first level. I know my time units are different, but this would be surprising to be the source of the error?
```{
dimensions:
        time = UNLIMITED ; // (1 currently)
        lon = 900 ;
        lat = 400 ;
        lev = 11 ;
        nhyi = 12 ;
        nhym = 11 ;
variables:
        double time(time) ;
                time:_FillValue = NaN ; // NaN
                time:standard_name = "time" ;
                time:axis = "T" ;
                time:units = "hours since 1970-01-01" ;
                time:calendar = "proleptic_gregorian" ;
                time:_Storage = "chunked" ;
                time:_ChunkSizes = 1 ;
                time:_Endianness = "little" ;
        double lon(lon) ;
                lon:_FillValue = NaN ;
                lon:standard_name = "longitude" ;
                lon:long_name = "longitude" ;
                lon:units = "degrees_east" ;
                lon:axis = "X" ;
                lon:_Storage = "chunked" ;
                lon:_ChunkSizes = 900 ;
                lon:_Endianness = "little" ;
        double lat(lat) ;
                lat:_FillValue = NaN ;
                lat:standard_name = "latitude" ;
                lat:long_name = "latitude" ;
                lat:units = "degrees_north" ;
                lat:axis = "Y" ;
                lat:_Storage = "chunked" ;
                lat:_ChunkSizes = 400 ;
                lat:_Endianness = "little" ;
        double lev(lev) ;
                lev:_FillValue = NaN ;
                lev:standard_name = "atmosphere_hybrid_sigma_pressure_coordinate" ;
                lev:units = "level" ;
                lev:positive = "down" ;
                lev:formula_terms = "ap: hyam b: hybm ps: PS" ;
                lev:_Storage = "chunked" ;
                lev:_ChunkSizes = 11 ;
                lev:_Endianness = "little" ;
        double hyai(nhyi) ;
                hyai:_FillValue = NaN ;
                hyai:long_name = "hybrid A coefficient at layer interfaces" ;
                hyai:units = "Pa" ;
                hyai:_Storage = "chunked" ;
                hyai:_ChunkSizes = 12 ;
                hyai:_Endianness = "little" ;
        double hybi(nhyi) ;
                hybi:_FillValue = NaN ;
                hybi:long_name = "hybrid B coefficient at layer interfaces" ;
                hybi:units = "1" ;
                hybi:_Storage = "chunked" ;
                hybi:_ChunkSizes = 12 ;
                hybi:_Endianness = "little" ;
        double hyam(nhym) ;
                hyam:_FillValue = NaN ;
                hyam:long_name = "hybrid A coefficient at layer midpoints" ;
                hyam:units = "hPa" ;
                hyam:_Storage = "chunked" ;
                hyam:_ChunkSizes = 11 ;
                hyam:_Endianness = "little" ;
        double hybm(nhym) ;
                hybm:_FillValue = NaN ;
                hybm:long_name = "hybrid B coefficient at layer midpoints" ;
                hybm:units = "1" ;
                hybm:_Storage = "chunked" ;
                hybm:_ChunkSizes = 11 ;
                hybm:_Endianness = "little" ;
        double PS(time, lat, lon) ;
                PS:_FillValue = NaN ;
                PS:long_name = "surface pressure" ;
                PS:units = "hPa" ;
                PS:_Storage = "chunked" ;
                PS:_ChunkSizes = 1, 400, 900 ;
                PS:_Endianness = "little" ;
} ```

**Comment by jimmielin** [comment]
Hi @lfreese I'm not sure if this functionality of HEMCO is even currently used right now so it's hard to say the source of the error. Do you mind emailing me a sample file and a HEMCO config so I can try to replicate and debug the relevant parts of the code locally?

Additionally you could also try modifying `HEMCO_Config.rc` to verbosity 2 and see when it tries to load your inventory, if it's correctly reading the vertical levels and recognizing that they are not model levels, and `Using MESSy regridding`. This text should appear.

Thanks!
Haipeng

**Comment by jimmielin** [comment]
Hi Bob (@yantosca) I've found the issue. It seems like there is a hard coded code path that isn't very future-proof.

@lfreese's input files include netCDF attributes to specify explicit level interfaces (`hyai`, `hybi`, ...) and a # of levels (11 to be specific); however they get recognized as "model levels" by this piece of code:

**hcoio_read_std_mod.F90**
```fortran
       IF ( Lct%Dct%Dta%Levels == 0 ) THEN
          IsModelLevel = NC_ISMODELLEVEL( ncLun, LevName )

          ! ...

          ! Further check if the given number of vertical levels should be
          ! treated as model levels. This is the case if e.g. the nuber of
          ! levels found on the file exactly matches the number of vertical
          ! levels of the grid. Some of these assumptions are rather arbitrary.
          ! IsModelLev will stay True if is was set so in NC_ISMODELLEVEL
          ! above. (ckeller, 9/29/15)
          CALL ModelLev_Check( HcoState, nlev, IsModelLevel, RC )
```

As Christoph has written, some of the assumptions are rather arbitrary; the below is very arbitrary within the `NC_ISMODELLEVEL` call (`hco_interp_mod.F90`):
```fortran
    nz = State_Grid%NZ

    ! ....
    ! Other supported levels that depend on compiler flags
    ! Full grid
    IF ( nz == 72 ) THEN
       IF ( nlev <= 73 ) THEN
          IsModelLev = .TRUE.
       ENDIF

    ! Reduced grid
    ELSEIF ( nz == 47 ) THEN
       IF ( nlev == 72 .OR. &
            nlev == 73 .OR. &
            nlev <= 47       ) THEN
          IsModelLev = .TRUE.
       ENDIF
    ENDIF
```

Note the `nlev <= 73` essentially makes **all input files with vertical levels less than the number of model levels** be recognized as **model levels**, and this is clearly not the case if levels are explicitly specified in the netCDF file!

This is the source of the bug which causes HEMCO to incorrectly use `map_a2a` regridding in the horizontal, and `MODELLEV_INTERPOLATE` in the vertical, which fails because 11 -> 72 (or 47) is an unsupported configuration.

Thus I recommend a fix in the model level check to override `IsModelLevel` in `hcoio_read_std_mod.F90` to `.false.` whenever **sigma levels that are explicit** are defined in the netCDF file. Note that we can't just remove `nlev <= 73` here unfortunately ... as AEIC emissions don't have sigma levels specified, but have `nlev = 10` or something like that. So these still have to be recognized as model levels as they were vertically interpolated offline.

Note that this fix was applied in some way for WRF-GC and HEMCO-CESM already, due to their model levels being defined at run time, and thus it's "impossible" for input netCDF to be on "model levels"; that patch was done a little further down the code. Please see this commit for reference: https://github.com/geoschem/HEMCO/commit/e77b8bf26ff0c58e82c96766bdce07fe4b1a930a#diff-b089cf2210fd24387669c5a2db4b226d

For the 2016 emissions data set to work, either off-line regridding to GEOS-Chem model levels is necessary (I would like to discourage this for future compatibility of the data set with HEMCO-CESM/WRF-GC) or a code fix needs to be applied to correctly recognize this case and use MESSy regridding.

Best,
Haipeng

**Comment by yantosca** [comment]
Thanks @jimmielin.  So if I understand you correctly, I should change:

```F90
    ! ....
    ! Other supported levels that depend on compiler flags
    ! Full grid
    IF ( nz == 72 ) THEN
       IF ( nlev <= 73 ) THEN
          IsModelLev = .TRUE.
       ENDIF
```
to
```F90
    ! ....
    ! Other supported levels that depend on compiler flags
    ! Full grid
    IF ( nz == 72 ) THEN
       IF ( nlev <= 73 ) THEN
          IsModelLev = .FALSE.
       ENDIF
```
Is there anywhere else this should be done?

**Comment by jimmielin** [comment]
Hi Bob, I think just changing it like that may break the AEIC emissions which are fed in using the model levels. Perhaps it is better to add a clause below the checks in `hcoio_read_std_mod.F90` here:

```fortran
          IsModelLevel = NC_ISMODELLEVEL( ncLun, LevName )

          ! Further check if the given number of vertical levels should be
          ! treated as model levels. This is the case if e.g. the nuber of
          ! levels found on the file exactly matches the number of vertical
          ! levels of the grid. Some of these assumptions are rather arbitrary.
          ! IsModelLev will stay True if is was set so in NC_ISMODELLEVEL
          ! above. (ckeller, 9/29/15)
          CALL ModelLev_Check( HcoState, nlev, IsModelLevel, RC )
          IF ( RC /= HCO_SUCCESS ) RETURN

          ! Check if sigma levels are specified in the file. If so, then set IsModelLevel = .false.
          ! ...
```

To add a check for sigma levels. I suggest we could copy the function `NC_ISMODELLEVEL` (in `ncdf_mod.F90`) to a new function `NC_ISSIGMALEVEL`, and use that to check if the unit for lev is `atmosphere_hybrid_sigma_pressure_coordinate`. Then we can just do
```fortran
IF(NC_ISSIGMALEVEL( ncLun, LevName )) IsModelLevel = .false.
```

**Comment by yantosca** [comment]
Thanks @jimmielin .  I implemented it this way and will test.  Stay tuned.
```F90
       ! Are these model levels? This will only return true if the long
       ! name of the level variable contains "GEOS-Chem level".
       ! For now, we assume levels are already on model levels if the
       ! number of levels to be read is explicitly set in the configuration
       ! file (ckeller, 5/20/15).
       IF ( Lct%Dct%Dta%Levels == 0 ) THEN
          IsModelLevel = NC_ISMODELLEVEL( ncLun, LevName )
      
          ! Further check if the given number of vertical levels should be
          ! treated as model levels. This is the case if e.g. the nuber of
          ! levels found on the file exactly matches the number of vertical
          ! levels of the grid. Some of these assumptions are rather arbitrary.
          ! IsModelLev will stay True if is was set so in NC_ISMODELLEVEL
          ! above. (ckeller, 9/29/15)
          CALL ModelLev_Check( HcoState, nlev, IsModelLevel, RC )
          IF ( RC /= HCO_SUCCESS ) RETURN

          ! Override IsModelLevel if the long_name contains
          ! "atmospheric_hybrid_sigma_pressure_coordinate"
          IsModelLevel = ( .not. NC_IsSigmaLevel( ncLun, LevName ) )

          ! Set level indeces to be read
          lev1 = 1
          lev2 = nlev

       ! If levels are explicitly given:
       ELSE
          
          ! If long_name is "atmospheric_hybrid_sigma_pressure_coordinate",
          ! then treat it as sigma levels; otherwise assume model levels.
          IsModelLevel = ( .not. NC_IsSigmaLevel( ncLun, LevName ) )

          ! Number of levels to be read must be smaller or equal to total
          ! number of available levels
          IF ( ABS(Lct%Dct%Dta%Levels) > nlev ) THEN
             WRITE(MSG,*) Lct%Dct%Dta%Levels, ' levels requested but file ', &
                'has only ', nlev, ' levels: ', TRIM(Lct%Dct%cName)
             CALL HCO_ERROR( HcoState%Config%Err, MSG, RC )
             RETURN
          ENDIF

          ! Set levels to be read
          IF ( Lct%Dct%Dta%Levels > 0 ) THEN
             lev1 = 1
             lev2 = Lct%Dct%Dta%Levels

          ! Reverse axis!
          ELSE
             lev1 = nlev
             lev2 = nlev + Lct%Dct%Dta%Levels + 1
          ENDIF

       ENDIF
```

**Comment by yantosca** [comment]
I have pushed a fix for this issue to:
- GEOS-Chem repo: https://github.com/geoschem/geos-chem/commit/f45a4670229518c4543edff47659b45468e6fcd7
- HEMCO repo: https://github.com/geoschem/HEMCO/commit/f86abaef8a0e60f41c94ad55b224fe7d7dcbb47c

So this should take care of it.  Let me know if it doesn't.

**Comment by lfreese** [comment]
Thanks @yantosca and @jimmielin for the help with this! I'll pull these latest updates and try them out.

**Comment by yantosca** [comment]
If you get it to work let me know and I will close this issue and release 12.9.3.

**Comment by lfreese** [comment]
Hi @yantosca-- It's still not reading in fully correct. I think this is due to there being a mixture of the standard name of "atmospheric_hybrid_sigma_pressure_coordinate" and "atmosphere_hybrid_sigma_pressure_coordinate" (eg: line 5076 uses the former and line 2444 and 2506 have the latter in https://github.com/geoschem/geos-chem/blob/dev/12.9.3/NcdfUtil/ncdf_mod.F90#L2444). It's unclear to me which of the two standard names I should name the levels in order to get it read as sigma levels properly from that.

**Comment by yantosca** [comment]
Hi @lfreese.  Thanks for pointing this out.  I just looked up the [CF standard names page](https://cfconventions.org/Data/cf-standard-names/73/build/cf-standard-name-table.html) and it is indeed `atmosphere_hybrid_sigma_pressure_coordinate`.

I will make this fix in dev/12.9.3 (GEOS-Chem) and HEMCO (dev/GC_13.0.0) repositories.  I haven't released 12.9.3 yet, so we still have time to make the fix.

You may need to use ncatted to rename the lev:long_name attribute in your file (from `atmospheric_` to `atmosphere_`), and then it should work.

**Comment by yantosca** [comment]
Also you might want to define

```
lev:standard_name = 'atmosphere_hybrid_sigma_pressure_coordinate`
lev:long_name = `atmosphere_hybrid_sigma_pressure_coordinate`

because the CF conventions also use standard_name to denote the [CF standard names](https://cfconventions.org/Data/cf-standard-names/73/build/cf-standard-name-table.html).

**Comment by yantosca** [comment]
Also @lfreese if you send me a copy of the file you are working with I can test it on my end.

**Comment by lfreese** [comment]
That makes sense. Okay so I've updated to using 'atmosphere_hybrid_sigma_pressure_coordinate' for both long and standard names. What is the best way to send a .nc file, as I can't upload that to github? I can send a dropbox link if that works, but via email. Below is the HEMCO setup being used in place of the typical NEI 2011 monthly files.

[EPA_Config.txt](https://github.com/geoschem/geos-chem/files/5023814/EPA_Config.txt)

**Comment by yantosca** [comment]
Dropbox should be fine.  Or if you have an public FTP server I can grab it from there.

Am also going to try to add the modification to check both standard_name and long_name attributes for `atmosphere_hybrid_sigma_pressure_coordinate`. 

 Long story short, we typically use COARDS conventions for netCDF.  But the CF conventions are a super-set of COARDS and include a lot of pre-defined standard names for quantities.  This makes it easier to share files but a headache if your data isn't covered by those pre-defined names.  So for HEMCO we usually just ask for COARDS but not CF.... except I guess for the case of non-standard vertical grids such as in your instance.

**Comment by lfreese** [comment]
Makes sense--hopefully when we finish these it will make a good example of how to prep vertical files for others who might face similar issues otherwise with the attributes. 

I sent you a dropbox link via email that contains the files.

**Comment by yantosca** [comment]
Thanks @lfreese.  I got the files.  Having some internet issues on my end, maybe related to TS Isaias.  I will test in the HEMCO standalone and see if it distributes the emissions in the vertical.

**Comment by yantosca** [comment]
I was finally able to test this.  With the updates I made to look at both the "standard_name" and "long_name" attributes, the HEMCO standalone was able to place emissions in the vertical.

CO, surface
![surface](https://user-images.githubusercontent.com/5880296/89346749-9192f100-d677-11ea-98f7-0dfd10af7e46.png)

CO, GEOS-Chem level 3
![gc_level_3](https://user-images.githubusercontent.com/5880296/89346761-9788d200-d677-11ea-9adf-fe58fc1fb467.png)

The commits are
- GEOS-Chem repo: 2e46145c7abfe5c66c8d0a1c9262e472610294be
- HEMCO repo: https://github.com/geoschem/HEMCO/commit/ab65bc821e6ce92148000677116d7f2bfa7e84e1

You can download the standalone HEMCO and create a run directory (see the run folder and execute the ../createRunDir.sh script and follow the prompts).  Then you can include your HEMCO_Config.rc into HEMCO_sa_Config.rc and type 
```
./hemco_standalone -c HEMCO_sa_Config.rc
```
Let me know if this works.  If so I'll go ahead to release 12.9.3.

**Comment by lfreese** [comment]
I was testing it on the GEOS-Chem (our cluster uses a newer version of HDF4 that is creating issues with HEMCO standalone that I'm trying to separately fix) and got this error:

```ncdf_mod.F90(2409): error #5082: Syntax error, found '.' when expecting one of: <LABEL> <END-OF-STATEMENT> ; TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE ...
.    LOGICAL            :: found
^
ncdf_mod.F90(2301): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [SIGLEV8]
  CALL NC_GET_SIGMA_LEVELS_C( fID,  ncFile, levName, lon1, lon2, lat1, &
-------^
ncdf_mod.F90(2378): error #6404: This name does not have a type, and must have an explicit type.   [SIGLEV8]
                                    SigLev4, SigLev8 )
---------------------------------------------^
ncdf_mod.F90(2350): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [SIGLEV]
                              SigLev8=SigLev )
--------------------------------------^
ncdf_mod.F90(2427): error #6404: This name does not have a type, and must have an explicit type.   [FOUND]
    found = Ncdoes_Var_Exist( fID, TRIM(levName) )
----^
ncdf_mod.F90(2427): error #6303: The assignment operation or the binary expression operation is invalid for the data types of the two operands.
    found = Ncdoes_Var_Exist( fID, TRIM(levName) )
------------^
ncdf_mod.F90(2442): error #6303: The assignment operation or the binary expression operation is invalid for the data types of the two operands.
    found  = NcDoes_Attr_Exist( fId, TRIM(levName), TRIM(a_name), a_type )
-------------^
ncdf_mod.F90(2447): error #6303: The assignment operation or the binary expression operation is invalid for the data types of the two operands.
       found  = NcDoes_Attr_Exist( fId, TRIM(levName), TRIM(a_name), a_type )
----------------^
ncdf_mod.F90(2473): error #6802: The argument to the PRESENT intrinsic function shall be the name of an optional dummy argument of the procedure in which the PRESENT function reference appears.   [SIGLEV8]
       ELSE IF ( PRESENT( SigLev8 ) ) THEN
--------------------------^
ncdf_mod.F90(2478): error #6691: A pointer dummy argument may only be argument associated with a pointer.   [SIGLEV8]
                                       time,  dir,    RC,   SigLev8=SigLev8 )
--------------------------------------------------------------------^
ncdf_mod.F90(2478): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [SIGLEV8]
                                       time,  dir,    RC,   SigLev8=SigLev8 )
--------------------------------------------------------------------^
compilation aborted for ncdf_mod.F90 (code 1)```

Which looks like it is due to the sigma level changes.

**Comment by yantosca** [comment]
Hi @lfreese.  I have seen that type of error before.  It is basically saying that the compiler does not like the syntax because it is using a newer Fortran standard.  I can push a fix later.

**Comment by msulprizio** [comment]
@lfreese The period at the beginning of the line `.    LOGICAL            :: found` in NcdfUtil/ncdf_mod.F90 should not be there. Try removing the punctuation and recompiling. We will fix this on our end too.

**Comment by yantosca** [comment]
I've fixed this bug in commit b95926b8b53d27817090c36e1c9f939110ce03f1.  This was only in the geoschem/geos-chem repo, but not in the geoschem/HEMCO repo.  So if you were using the HEMCO standalone from the geoschem/HEMCO repository, you should not have been affected.

Sorry.... at first I didn't notice the `.` character.  Somehow that caused an error that I have seen before in a different context, when trying to compile HEMCO with newer compiler versions.  Oh well.

**Comment by yantosca** [comment]
I will close this issue as we are including this fix into 12.9.3.

**Comment by lfreese** [comment]
Thank you! Sorry I was away, but thanks again for all of the help in getting this set up.

**Comment by lfreese** [comment]
Thank you! Sorry I was away, but thanks again for all of the help in getting this set up. @yantosca One additional comment in regards to the test you ran above--the tests that I do still only have emissions above the surface level for 'Total' emissions, while having zero in the Anthro category, for example 'EmisCO_Anthro'. I would expect these to be non-zero as I have these categorized as Anthropogenic emissions (cat = 1).
