### ISSUE TITLE
[BUG/ISSUE]Strange missing file is required in running  full chemistry simulation 

### ISSUE THREAD

**Issue by xiaoyu-ss** [geoschem/geos-chem#653]
# Report a GEOS-Chem bug or technical issue

### Expected behavior: ###

I am running a full chemistry simulation from 20160101 to 20160102 in 2x2.5 degrees resolution in GEOS-Chem13.0.0.

### Actual behavior: ###

Then the simulation stopped with the error message indicating the missing file.  I do the dry-run simulation, and find that a strange file is required, "UCX (SFCMR_READ): REQUIRED FILE NOT FOUND /mnt/raid/geoschem/GC/gcgrid/data/ExtData/CHEM_INPUTS/UCX_201403/NoonTime/Grid2x25/InitCFC_ ".
The dry-run log file is attached.

Could you can give some suggestions on this problem? Thanks.

### Error messages

```
 Error in ReadList_Read called from hco_run
===============================================================================
GEOS-Chem ERROR: Error encountered in "HCO_Run"!
 -> at HCOI_GC_Run (in module GeosCore/hco_interface_gc_mod.F90)

THIS ERROR ORIGINATED IN HEMCO!  Please check the HEMCO log file for 
additional error messages!
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "HCOI_GC_Run"!
 -> at Emissions_Run (in module GeosCore/emissions_mod.F90)
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "Emissions_Run", Phase 0

This error can indicate a missing file. Please check the HEMCO log file for 
additional error messages!

STOP at  -> at GEOS-Chem (in GeosCore/main.F90)
===============================================================================
```

### Input and log files to attach

 - lastbuild: 2021/3/15
 - input.geos: [input.geos.txt](https://github.com/geoschem/geos-chem/files/6139916/input.geos.txt)
 - HEMCO_Config.rc: 
[HEMCO.log](https://github.com/geoschem/geos-chem/files/6140009/HEMCO.log)
__
 - GEOS-Chem "Classic" log file: 
[GC.log.txt](https://github.com/geoschem/geos-chem/files/6139922/GC.log.txt)

 - Any other error messages: __
[dry-run.log.txt](https://github.com/geoschem/geos-chem/files/6139924/dry-run.log.txt)

**Comment by WilliamDowns** [comment]
I believe this issue was addressed in [https://github.com/geoschem/geos-chem/commit/1c4f40698978c02462622bbb36e12a37c2c98fb0](https://github.com/geoschem/geos-chem/commit/1c4f40698978c02462622bbb36e12a37c2c98fb0). Are you using version 13.0.0-rc.1? The fix is not in that release (or on the main branch yet). You can try checking out the `dev/13.0.0-final` branch to fix this issue. You'll need to recompile your code and may need to recreate your run directory as well.

**Comment by xiaoyu-ss** [comment]
Thanks for the suggesstion. I cloned the GCClassic superproject repository from github and set the branch as 'dev/13.0.0-final' to my local disk as the wiki page. And I recompiled my code and recreated the run directory. But the same problem still arose. 

By the way, I suppose if people follow the process to clone the code as wiki page says, they will not get the final version as you mention. I guess  maybe the default branch of GCClassic is not the final version?

**Comment by WilliamDowns** [comment]
Can you post copies of your log files again? Based on your original HEMCO.log file, it's possible the restart file isn't downloading properly (as reported in [https://github.com/geoschem/geos-chem/issues/628](https://github.com/geoschem/geos-chem/issues/628)). Also just to confirm, are you doing the `./download_data.py log.dryrun` step of the dry-run workflow?

Regarding the versioning of the code, the `dev/13.0.0-final` branch is a development branch that has not been fully tested to our standards for release. The steps on the Wiki will always lead users to downloading the latest verified stable release version.

**Comment by WilliamDowns** [comment]
After testing a bit, your error is probably due to the dry-run looking for the wrong restart filename due to some changes in 13.0.0. Try doing `wget http://geoschemdata.computecanada.ca/ExtData/GEOSCHEM_RESTARTS/v2018-11/initial_GEOSChem_rst.4x5_standard.nc GEOSChem.Restart.20160101_0000z.nc4` in your run directory and see if that new file fixes the issue

**Comment by yantosca** [comment]
We are about to release 13.0.0 soon, so we can add a fix for this in patch version 13.0.1.  There are some other minor fixes that will go into that version as well.

**Comment by xiaoyu-ss** [comment]
Thanks very much for the reply and suggestions.
I try 'wget http://ftp.as.harvard.edu/gcgrid/geos-chem/10yr_benchmarks/13.0.0-rc.0/GCClassic/restarts/GEOSChem.Restart.2
0160101_0000z.nc4', and do the dryrun. So the restart file is not missing according to the log. But the it still informs me about the missing file 'InitCFC_', and it is the same problem as before. 
This is my new dryrun log file. Thanks for checking the log file again.
[log.txt](https://github.com/geoschem/geos-chem/files/6155450/log.txt)

**Comment by WilliamDowns** [comment]
Thanks for reporting that that file (which is not a real file) is still being reported as missing. We'll fix that. However, your run should be able to complete now (or at least progress beyond reading input files) because your new log indicates the only missing file is that fake file. What happens if you run the model normally, i.e. `./gcclassic | tee run.log`?

**Comment by xiaoyu-ss** [comment]
Thanks for the suggestion. I run the model normally and it succeeds. So the reporting from the dry-run log have no influence on the real simulation.

**Comment by yantosca** [comment]
@xiaoyu-ss, @WilliamDowns: These dry-run issues are now resolved by Pull Request #661.  This will go into patch version 13.0.1, along with some other fixes for minor issues.

I will close this issue now as the PR has been submitted.
